import './globals.css'
import Navigation from './components/Navigation.jsx'

export const metadata = {
  title: 'Learn Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
          {children}
      </body>
    </html>
  )
}
